// personal-ledger-uniapp/src/components/EmptyState.vue
<template>
	<view class="empty-state">
		<view class="empty-icon-wrap">
			<text class="empty-icon">{{ icon }}</text>
		</view>
		<text class="empty-title">{{ title }}</text>
		<text v-if="description" class="empty-desc">{{ description }}</text>
		<view v-if="$slots.action" class="empty-action">
			<slot name="action"></slot>
		</view>
	</view>
</template>

<script>
export default {
	name: 'EmptyState',
	props: {
		icon: {
			type: String,
			default: '📄',
		},
		title: {
			type: String,
			default: '暂无数据',
		},
		description: {
			type: String,
			default: '',
		},
	},
}
</script>

<style scoped>
.empty-state {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 100rpx var(--space-2xl) 80rpx;
}

/* 图标容器：渐变圆形 */
.empty-icon-wrap {
	width: 120rpx;
	height: 120rpx;
	border-radius: var(--radius-full);
	background: var(--color-bg);
	display: flex;
	align-items: center;
	justify-content: center;
	margin-bottom: var(--space-xl);
}

.empty-icon {
	font-size: 56rpx;
	display: block;
	opacity: 0.9;
}

.empty-title {
	font-size: var(--font-base);
	font-weight: var(--weight-semibold);
	color: var(--color-text-heading);
	display: block;
	margin-bottom: var(--space-sm);
	letter-spacing: var(--tracking-heading);
	line-height: var(--leading-tight);
}

.empty-desc {
	font-size: var(--font-xs);
	color: var(--color-text-tertiary);
	display: block;
	margin-bottom: var(--space-xl);
	text-align: center;
	line-height: var(--leading-relaxed);
	max-width: 440rpx;
}

.empty-action {
	margin-top: var(--space-sm);
}
</style>

// personal-ledger-frontend/src/components/ui/EmptyState.jsx
import { Empty, Button, Typography } from 'antd'

const { Text } = Typography

/**
 * EmptyState - Styled empty state with icon, title, description & optional CTA
 *
 * @param {Object} props
 * @param {string} [props.title='暂无数据'] - Main heading
 * @param {string} [props.description] - Subtitle / descriptive paragraph
 * @param {ReactNode} [props.action] - Action button or custom node
 * @param {string|ReactNode} [props.image] - Custom image (uses AntD default if omitted)
 * @param {string} [props.size='large'] - Size of the empty illustration
 */
export default function EmptyState({
  title = '暂无数据',
  description,
  action,
  image,
  size = 'large',
}) {
  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 'var(--space-4xl) var(--space-xl)',
      minHeight: '240px',
    }}>
      <Empty
        image={image || Empty.PRESENTED_IMAGE_SIMPLE}
        imageStyle={{
          height: size === 'large' ? 96 : 60,
          marginBottom: 'var(--space-lg)',
          opacity: 0.6,
        }}
        description={
          <div style={{ textAlign: 'center' }}>
            <Text strong style={{
              fontSize: 'var(--font-size-lg)',
              color: 'var(--color-text)',
              display: 'block',
              marginBottom: description ? 'var(--space-xs)' : 0,
            }}>
              {title}
            </Text>
            {description && (
              <Text type="secondary" style={{
                fontSize: 'var(--font-size-base)',
                lineHeight: 'var(--line-height-relaxed)',
              }}>
                {description}
              </Text>
            )}
          </div>
        }
      >
        {action}
      </Empty>
    </div>
  )
}
