// personal-ledger-uniapp/src/pages/login/index.vue
<template>
	<view class="container">
		<view class="header">
			<text class="title">个人记账本</text>
			<text class="subtitle">记录每一笔收支</text>
		</view>

		<view class="form-card">
			<view class="input-group">
				<text class="label">用户名</text>
				<input
					class="input"
					v-model="username"
					placeholder="请输入用户名"
					placeholder-class="placeholder"
				/>
			</view>

			<view class="input-group">
				<text class="label">密码</text>
				<input
					class="input"
					v-model="password"
					placeholder="请输入密码"
					placeholder-class="placeholder"
					:password="true"
				/>
			</view>

			<button
				class="btn-primary"
				:loading="submitting"
				:disabled="submitting"
				@click="handleLogin"
			>
				登录
			</button>

			<view class="link" @click="goRegister">
				<text class="link-text">还没有账号？</text>
				<text class="link-highlight">立即注册</text>
			</view>
		</view>
	</view>
</template>

<script>
import { login } from '../../api/user'
import { useUserStore } from '../../utils/store'

export default {
	data() {
		return {
			username: '',
			password: '',
			submitting: false,
		}
	},
	onLoad() {
		// 已登录则直接跳主页，避免在登录页卡住
		const token = uni.getStorageSync('token')
		if (token) {
			uni.switchTab({ url: '/pages/dashboard/index' })
		}
	},
	methods: {
		async handleLogin() {
			if (!this.username || !this.password) {
				uni.showToast({ title: '请输入用户名和密码', icon: 'none' })
				return
			}
			this.submitting = true
			try {
				const res = await login({
					username: this.username,
					password: this.password
				})
				if (res.code === 200) {
					const store = useUserStore()
					store.setToken(res.data)
					await store.fetchUserInfo()
					uni.switchTab({ url: '/pages/dashboard/index' })
				} else {
					uni.showToast({ title: res.message || '登录失败', icon: 'none' })
				}
			} catch (e) {
				uni.showToast({ title: '网络连接失败', icon: 'none' })
			} finally {
				this.submitting = false
			}
		},
		goRegister() {
			uni.navigateTo({ url: '/pages/register/index' })
		}
	}
}
</script>

<style scoped>
.container {
	min-height: 100vh;
	background-color: var(--color-bg);
	display: flex;
	flex-direction: column;
	justify-content: center;
	padding: 80rpx var(--space-3xl);
}

/* ── 头部 ── */
.header {
	text-align: center;
	margin-bottom: 80rpx;
}

.title {
	font-size: var(--font-5xl);
	font-weight: var(--weight-extrabold);
	color: var(--color-text-heading);
	display: block;
	letter-spacing: var(--tracking-heading);
	line-height: var(--leading-tight);
}

.subtitle {
	font-size: var(--font-md);
	color: var(--color-text-secondary);
	margin-top: var(--space-md);
	display: block;
	font-weight: var(--weight-medium);
	letter-spacing: var(--tracking-caption);
}

/* ── 表单卡片 ── */
.form-card {
	background-color: var(--color-surface);
	border-radius: var(--radius-2xl);
	padding: var(--space-3xl);
	box-shadow: var(--shadow-sm);
}

.input-group {
	margin-bottom: var(--space-xl);
}

.label {
	font-size: var(--font-base);
	font-weight: var(--weight-semibold);
	color: var(--color-text);
	margin-bottom: var(--space-sm);
	display: block;
}

.input {
	height: 88rpx;
	border: 2rpx solid var(--color-border-input);
	border-radius: var(--radius-md);
	padding: 0 var(--space-lg);
	font-size: var(--font-lg);
	color: var(--color-text);
	background-color: var(--color-bg);
	transition: border-color var(--transition-fast);
}

/* 输入框激活效果用 focus 伪类的话 uni-app 支持有限，靠原生 */
.input:focus {
	border-color: var(--color-primary);
}

.placeholder {
	color: var(--color-text-tertiary);
	font-size: var(--font-base);
}

/* ── 登录按钮 ── */
.btn-primary {
	margin-top: var(--space-md);
	height: 88rpx;
	line-height: 88rpx;
	background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
	color: var(--color-text-inverse);
	font-size: var(--font-lg);
	font-weight: var(--weight-bold);
	border-radius: var(--radius-lg);
	border: none;
	box-shadow: var(--shadow-accent);
	transition: transform var(--transition-spring), opacity var(--transition-fast);
}

.btn-primary::after {
	border: none;
}

.btn-primary:active {
	transform: scale(0.97);
}

.btn-primary[disabled] {
	opacity: 0.6;
}

/* ── 注册链接 ── */
.link {
	text-align: center;
	margin-top: var(--space-2xl);
}

.link-text {
	font-size: var(--font-md);
	color: var(--color-text-secondary);
}

.link-highlight {
	font-size: var(--font-md);
	color: var(--color-accent);
	font-weight: var(--weight-semibold);
	margin-left: var(--space-xs);
}
</style>

// personal-ledger-frontend/src/pages/Login.jsx
import { Form, Input, Button, Typography, App as AntdApp } from 'antd'
import { UserOutlined, LockOutlined, WalletOutlined } from '@ant-design/icons'
import { useNavigate, Link } from 'react-router-dom'
import { login } from '../api/user'
import { useAuth } from '../context/AuthContext'

const { Title, Text } = Typography

export default function Login() {
  const [form] = Form.useForm()
  const navigate = useNavigate()
  const { setUser, fetchUserInfo } = useAuth()
  const { message } = AntdApp.useApp()

  const onFinish = async (values) => {
    try {
      const res = await login(values)
      if (res.code === 200) {
        localStorage.setItem('token', res.data.token)
        message.success('登录成功')
        await fetchUserInfo()
        navigate('/', { replace: true })
      } else {
        message.error(res.message)
      }
    } catch (error) {
      message.error(error?.response?.data?.message || '登录失败，请稍后重试')
    }
  }

  return (
    <div style={{
      display: 'flex',
      minHeight: '100vh',
      background: 'var(--color-bg)',
    }}>
      {/* 左侧品牌区域 */}
      <div style={{
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        background: 'linear-gradient(135deg, var(--color-primary) 0%, #16213e 100%)',
        padding: '60px',
        position: 'relative',
        overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute',
          top: '10%',
          left: '10%',
          width: 300,
          height: 300,
          borderRadius: '50%',
          background: 'rgba(255, 255, 255, 0.03)',
        }} />
        <div style={{
          position: 'absolute',
          bottom: '20%',
          right: '15%',
          width: 200,
          height: 200,
          borderRadius: '50%',
          background: 'rgba(255, 255, 255, 0.03)',
        }} />
        <div style={{ textAlign: 'center', position: 'relative', zIndex: 1 }}>
          <div style={{
            width: 80,
            height: 80,
            borderRadius: 'var(--radius-lg)',
            background: 'rgba(255, 255, 255, 0.1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 32,
            margin: '0 auto 32px',
          }}>
            <WalletOutlined style={{ fontSize: 36, color: '#fff' }} />
          </div>
          <Title level={2} style={{ color: '#fff', marginBottom: 16, fontWeight: 700 }}>
            个人记账本
          </Title>
          <Text style={{ color: 'rgba(255, 255, 255, 0.7)', fontSize: 16 }}>
            简洁高效的个人财务管理工具
          </Text>
        </div>
      </div>

      {/* 右侧登录表单 */}
      <div style={{
        width: 480,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 60,
        background: 'var(--color-surface)',
      }}>
        <div style={{ width: '100%', maxWidth: 360 }}>
          <div style={{ marginBottom: 48 }}>
            <Title level={3} style={{ marginBottom: 8, fontWeight: 700, color: 'var(--color-text)' }}>
              欢迎回来
            </Title>
            <Text style={{ color: 'var(--color-text-secondary)', fontSize: 15 }}>
              登录您的账户以继续
            </Text>
          </div>

          <Form form={form} onFinish={onFinish} size="large" layout="vertical">
            <Form.Item name="username" style={{ marginBottom: 20 }}>
              <Input
                prefix={<UserOutlined style={{ color: 'var(--color-text-tertiary)' }} />}
                placeholder="用户名"
                style={{ height: 48, borderRadius: 'var(--radius-md)' }}
              />
            </Form.Item>
            <Form.Item name="password" style={{ marginBottom: 28 }}>
              <Input.Password
                prefix={<LockOutlined style={{ color: 'var(--color-text-tertiary)' }} />}
                placeholder="密码"
                style={{ height: 48, borderRadius: 'var(--radius-md)' }}
              />
            </Form.Item>
            <Form.Item style={{ marginBottom: 20 }}>
              <Button
                type="primary"
                htmlType="submit"
                block
                style={{ height: 48, fontSize: 16, fontWeight: 600 }}
              >
                登录
              </Button>
            </Form.Item>
            <div style={{ textAlign: 'center' }}>
              <Text style={{ color: 'var(--color-text-secondary)' }}>
                还没有账号？
              </Text>
              <Link
                to="/register"
                style={{
                  color: 'var(--color-primary)',
                  fontWeight: 600,
                  marginLeft: 4,
                }}
              >
                立即注册
              </Link>
            </div>
          </Form>
        </div>
      </div>
    </div>
  )
}
